<!DOCTYPE html>
<html lang="en">
<body>
<?php
$blockObj= $block->getLayout()->createBlock('Ambab\EmiCalculator\Block\Catalog\Product\Price');
?>

<div id="header-mpdal" class="container">

<div id="element" data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": false, "multipleCollapsible": false}}'>
    
<?php


   $datacollection=$block->BankData(); 
   $a = array();   
    foreach ($datacollection as $data) {
        $bankname = $data->getBankName();
        
?>

<div data-role="collapsible" id="row">

        <div data-role="trigger">
           <span><?php echo strtoupper($bankname);?></span>
        </div>
    </div>

    <div data-role="content" class="content">
        <table id="customers">
  
    <tr>
      
      <th scope="col">EMI Plan</th>
      <th scope="col">Interest(Pa)</th>
      <th scope="col">Product Price</th>
      <th scope="col">Total Price</th>
    </tr>
 
  
    <?php
        $datacollection1=$block->BankDetails($bankname);
        foreach ($datacollection1 as $res){
            $rate = $res->getRateOfInt();
            $term = $res->getMonth();
            $amount = $blockObj->getProductPrice();
            $emiarr = $block->EmiCalculation($rate,$term,$amount); 
            array_push($a,$emiarr[0]);
    ?>
    <tr>
      
      <td><?php echo $emiarr[0].'x'.$term.'m'; ?></td>
      <td><?php echo '('.ceil($emiarr[1]).'Rs'.')'.' '.$res->getMonth().'%'; ?></td>
      <td><?php echo ceil($amount).' '.'Rs'; ?></td>
      <td><?php echo ceil($emiarr[2]).' '.'Rs'; ?></td>
    </tr>
    <?php
    }
?>

</table>
</div>
<?php
    }
    
?>
   
</div>
</div>
</body>
</html>
<?php if ($block->canShowBlock()): ?>
    <a href="#" id="click-header">
    Emi Starts From <?php echo min($a).' '.'Rs/Month'; ?>
</a>
<?php endif; ?>


<!-- <script>
    require(
    [
        'jquery',
        'Magento_Ui/js/modal/modal'
    ],
    function(
        $,
        modal
    ) {
        var options = {
            type: 'popup',
            responsive: true,
            innerScroll: true,
            title: '',
            buttons: [{
                text: $.mage.__('Close'),
                class: '',
                click: function () {
                    this.closeModal();
                }
            }]
        };

        var popup = modal(options, $('#header-mpdal'));
        $("#click-header").on('click',function(){ 
            $("#header-mpdal").modal("openModal");
        });

    }
);
</script> -->