<div id="popup" style="display: none;"> 
   <?php echo $this->getChildHtml('popup-content') ?> 

<?php
$blockObj= $block->getLayout()->createBlock('Ambab\EmiCalculator\Block\Catalog\Product\Price');
$blockview= $block->getLayout()->createBlock('Ambab\EmiCalculator\Block\Catalog\Product\View');
$emiEnable = $blockview->canShowBlock();
$amount = $blockObj->getOrdertotal();
?>

<div id="header-mpdal" class="container">

<div id="element" data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": false, "multipleCollapsible": false}}'>
    
<?php

   $datacollection=$blockview->BankData();  

    foreach ($datacollection as $data) {
        $bankname = $data->getBankName();        
?>

<div data-role="collapsible" id="row">

        <div data-role="trigger">
           <span><?php echo strtoupper($bankname);?></span>
        </div>
    </div>

    <div data-role="content" class="content">
        <table id="customers">
  
    <tr>
      
      <th scope="col">EMI Plan</th>
      <th scope="col">Interest(Pa)</th>
      <th scope="col">Order Price</th>
      <th scope="col">Total Price</th>
    </tr>
 
  
    <?php
        $datacollection1=$blockview->BankDetails($bankname);
        foreach ($datacollection1 as $res){
            $rate = $res->getRateOfInt();
            $term = $res->getMonth();
            $emiarr = $blockview->EmiCalculation($rate,$term,$amount);
            
            
            
    ?>
    <tr>
      
      <td><?php echo $emiarr[0].'x'.$term.'m'; ?></td>
      <td><?php echo '('.ceil($emiarr[1]).'Rs'.')'.' '.$res->getMonth().'%'; ?></td>
      <td><?php echo ceil($amount).' '.'Rs'; ?></td>
      <td><?php echo ceil($emiarr[2]).' '.'Rs'; ?></td>
    </tr>
    <?php
    }
?>

</table>
</div>
<?php
    }
    
?>
   
</div>
</div>

</div>
   
<script type="text/javascript">
    var Enable = <?php echo json_encode($emiEnable); ?>;
</script>
