<div id="popup" style="display: none;"> 
   <?php echo $this->getChildHtml('popup-content') ?> 

<?php
$blockObj= $block->getLayout()->createBlock('Ambab\EmiCalculator\Block\Catalog\Product\Price');
$blockh= $block->getLayout()->createBlock('Ambab\EmiCalculator\Block\Catalog\Product\View');
$amount = $blockObj->getSubtotal();
?>

<div id="header-mpdal" class="container">

<div id="element" data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": false, "multipleCollapsible": false}}'>
    
<?php

   $datacollection=$blockh->BankData();  

    foreach ($datacollection as $data) {
        $bankname = $data['bank_name'];        
?>

<div data-role="collapsible" id="row">

        <div data-role="trigger">
           <span><?php echo strtoupper($bankname);?></span>
        </div>
    </div>

    <div data-role="content" class="content">
        <table id="customers">
  
    <tr>
      
      <th scope="col">EMI Plan</th>
      <th scope="col">Interest(Pa)</th>
      <th scope="col">Total Cost</th>
    </tr>
 
  
    <?php
        $datacollection1=$blockh->BankDetails($bankname);
        foreach ($datacollection1 as $res){
            $var = $res['rate_of_int'];
            $rate = $var/(12*100);
            $term = $res['month'];
            $EMI = $blockh->EmiCalculation($rate,$term,$amount);
            $NewEMI = ceil($EMI);
            
            
    ?>
    <tr>
      
      <td><?php echo $NewEMI.'x'.$term.'m'; ?></td>
      <td><?php echo $res['rate_of_int'].'%'; ?></td>
      <td><?php echo ceil($amount).' '.'Rs'; ?></td>
    </tr>
    <?php
    }
?>

</table>
</div>
<?php
    }
    
?>
   
</div>
</div>

</div>